# Generated by Django 5.0 on 2024-10-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default=None, max_length=100)),
                ('permission_level', models.IntegerField(choices=[(1, 'Normal User'), (2, 'Map Editor'), (3, 'Map Manager')], default=1)),
            ],
        ),
    ]
