# Generated by Django 5.0 on 2024-08-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(1, 'Anonymous User'), (2, 'Normal User'), (3, 'Map Editor')])),
            ],
        ),
    ]
