# Generated by Django 5.0.8 on 2024-08-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_dummydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='map_editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('map', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='dummyData',
            new_name='map_data',
        ),
        migrations.RenameField(
            model_name='map_data',
            old_name='uid',
            new_name='map_data',
        ),
    ]
