# Generated by Django 5.0 on 2024-09-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_map_editor_rename_dummydata_map_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='map_data',
        ),
        migrations.DeleteModel(
            name='map_editor',
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='level',
            field=models.IntegerField(choices=[(1, 'Normal User'), (2, 'Map Editor'), (3, 'Map Manager')]),
        ),
    ]
