# Generated by Django 5.0 on 2024-09-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_map_data_delete_map_editor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('verified_status', models.BooleanField()),
                ('history', models.CharField(max_length=500)),
                ('editable_map', models.CharField(max_length=500)),
                ('managed_map', models.CharField(max_length=500)),
            ],
        ),
    ]
