# Generated by Django 5.0 on 2024-09-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_credential',
            fields=[
                ('uid', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('Legal_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
