# Generated by Django 5.0 on 2024-09-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_editable_map_alter_user_history_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userPermission',
        ),
        migrations.RemoveField(
            model_name='user',
            name='editable_map',
        ),
        migrations.RemoveField(
            model_name='user',
            name='history',
        ),
        migrations.RemoveField(
            model_name='user',
            name='managed_map',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified_status',
        ),
        migrations.AddField(
            model_name='user',
            name='permission_level',
            field=models.IntegerField(choices=[(1, 'Normal User'), (2, 'Map Editor'), (3, 'Map Manager')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
