# Generated by Django 5.0 on 2024-09-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_delete_userpermission_remove_user_editable_map_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_credential',
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
