# Generated by Django 5.0 on 2024-09-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='map_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(max_length=100)),
                ('map_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='map_editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('map', models.CharField(max_length=100)),
            ],
        ),
    ]
