# Generated by Django 5.0 on 2024-10-01 05:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maps',
            fields=[
                ('map_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('map_addr', models.CharField(max_length=100)),
                ('map_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='map_variation',
            fields=[
                ('map_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(default='', max_length=100)),
                ('map_data', models.CharField(default='', max_length=100)),
                ('map_editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='map_uploaded', to='authentication.user')),
                ('map_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='map_manager.maps')),
            ],
        ),
    ]
