# Generated by Django 5.0 on 2024-09-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('editor', models.CharField(max_length=500)),
                ('manager', models.CharField(max_length=500)),
                ('edges', models.CharField(max_length=100)),
                ('node', models.CharField(max_length=100)),
            ],
        ),
    ]
