# Generated by Django 5.0 on 2024-09-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_manager', '0002_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='id',
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
