# Generated by Django 5.0 on 2024-09-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_manager', '0003_remove_map_id_alter_map_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
