# Generated by Django 5.0 on 2024-09-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_manager', '0004_map_map_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='edges',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='map',
            name='editor',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='map',
            name='node',
            field=models.CharField(default='', max_length=100),
        ),
    ]
