# Generated by Django 5.0 on 2024-09-23 00:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_delete_user_credential_alter_user_uid_and_more'),
        ('map_manager', '0005_alter_map_edges_alter_map_editor_alter_map_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='map_variation',
            fields=[
                ('map_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('map_editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='map_uploaded', to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=100)),
                ('map_addr', models.CharField(max_length=100)),
                ('map_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='map',
        ),
        migrations.DeleteModel(
            name='map_data',
        ),
        migrations.DeleteModel(
            name='map_editor',
        ),
        migrations.AddField(
            model_name='map_variation',
            name='map_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='map_manager.maps'),
        ),
    ]
