# Generated by Django 5.0 on 2024-09-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_manager', '0006_map_variation_maps_delete_map_delete_map_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map_variation',
            old_name='map_name',
            new_name='map_info',
        ),
        migrations.AddField(
            model_name='map_variation',
            name='map_data',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='map_variation',
            name='version_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
